name = "telegram-group-bot"
main = "src/index.ts"
compatibility_date = "2024-10-22"

[ai]
binding = "AI"

[vars]
# Add your environment variables here
# TELEGRAM_BOT_TOKEN = "your_bot_token"
# TELEGRAM_WEBHOOK_SECRET = "your_webhook_secret"
# UPSTASH_REDIS_REST_URL = "your_redis_url"
# UPSTASH_REDIS_REST_TOKEN = "your_redis_token"
